require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sales_people", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SalesPerson. As you add validations to SalesPerson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Foo Bar", sales_office_id: SalesOffice.create(state: "Arizona").id } 
  }

  let(:invalid_attributes) {
    { name: "" } 
  }

  describe "GET /index" do
    it "renders a successful response" do
      SalesPerson.create! valid_attributes
      get sales_people_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sales_person = SalesPerson.create! valid_attributes
      get sales_person_url(sales_person)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sales_person_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sales_person = SalesPerson.create! valid_attributes
      get edit_sales_person_url(sales_person)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SalesPerson" do
        expect {
          post sales_people_url, params: { sales_person: valid_attributes }
        }.to change(SalesPerson, :count).by(1)
      end

      it "redirects to the created sales_person" do
        post sales_people_url, params: { sales_person: valid_attributes }
        expect(response).to redirect_to(sales_person_url(SalesPerson.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SalesPerson" do
        expect {
          post sales_people_url, params: { sales_person: invalid_attributes }
        }.to change(SalesPerson, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sales_people_url, params: { sales_person: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sales_person" do
      sales_person = SalesPerson.create! valid_attributes
      expect {
        delete sales_person_url(sales_person)
      }.to change(SalesPerson, :count).by(-1)
    end

    it "redirects to the sales_people list" do
      sales_person = SalesPerson.create! valid_attributes
      delete sales_person_url(sales_person)
      expect(response).to redirect_to(sales_people_url)
    end
  end
end
